/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/web/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import { expect, test } from '@playwright/test';

test.describe('Gist Loading', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test.describe('Load from Gist URL', () => {
    test('accepts a full gist.github.com URL in the Gist input field', async ({
      page,
    }) => {
      const gistInput = page.locator('input[placeholder*="gist"]');
      await expect(gistInput).toBeVisible();
      await gistInput.fill('https://gist.github.com/user/abc123');
      await expect(gistInput).toHaveValue(
        'https://gist.github.com/user/abc123'
      );
    });

    test('adds the loaded session to the sidebar on success', async ({
      page,
    }) => {
      const gistInput = page.locator('input[placeholder*="gist"]');
      await gistInput.fill('https://gist.github.com/user/abc123');

      const loadButton = page.getByRole('button', { name: 'load gist' });
      await loadButton.click();

      // This will fail because the gist doesn't exist, but we verify the flow works
      await page.waitForTimeout(3000);
    });
  });

  test.describe('Load from Gist ID', () => {
    test('accepts a bare Gist ID in the input field', async ({ page }) => {
      const gistInput = page.locator('input[placeholder*="gist"]');
      await gistInput.fill('abc123def456');
      await expect(gistInput).toHaveValue('abc123def456');
    });

    test('fetches and loads the session the same as with a full URL', async ({
      page,
    }) => {
      const gistInput = page.locator('input[placeholder*="gist"]');
      await gistInput.fill('nonexistent999999');

      const loadButton = page.getByRole('button', { name: 'load gist' });
      await loadButton.click();

      // Should attempt to fetch (and fail with an error, same behavior as URL)
      const errorMessage = page.locator('.text-status-error');
      await expect(errorMessage).toBeVisible({ timeout: 10_000 });
    });
  });

  test.describe('Error handling', () => {
    test('displays an error message when the Gist URL is invalid', async ({
      page,
    }) => {
      const gistInput = page.locator('input[placeholder*="gist"]');
      await gistInput.fill('not a valid url or id!!!');

      const loadButton = page.getByRole('button', { name: 'load gist' });
      await loadButton.click();

      const errorMessage = page.locator('.text-status-error');
      await expect(errorMessage).toBeVisible({ timeout: 5_000 });
      await expect(errorMessage).toContainText('Invalid');
    });

    test('displays an error message when the Gist cannot be fetched', async ({
      page,
    }) => {
      const gistInput = page.locator('input[placeholder*="gist"]');
      await gistInput.fill('https://gist.github.com/user/nonexistent999999');

      const loadButton = page.getByRole('button', { name: 'load gist' });
      await loadButton.click();

      // Wait for the error message to appear
      const errorMessage = page.locator('.text-status-error');
      await expect(errorMessage).toBeVisible({ timeout: 10_000 });
    });

    test('does not create a session entry when loading fails', async ({
      page,
    }) => {
      const gistInput = page.locator('input[placeholder*="gist"]');
      await gistInput.fill('https://gist.github.com/user/nonexistent999999');

      const loadButton = page.getByRole('button', { name: 'load gist' });
      await loadButton.click();

      // Wait for error
      await page.locator('.text-status-error').waitFor({ timeout: 10_000 });

      // Sidebar should still show 0 sessions
      const sidebar = page.locator('aside').first();
      await expect(sidebar.getByText('[0]')).toBeVisible();
    });
  });

  test.describe('Loading state', () => {
    test('shows a loading spinner on the load gist button while fetching', async ({
      page,
    }) => {
      // Intercept the GitHub API request and delay it to observe loading state
      await page.route('**/api.github.com/**', async route => {
        await new Promise(r => setTimeout(r, 3000));
        await route.fulfill({ status: 404, body: 'Not found' });
      });

      const gistInput = page.locator('input[placeholder*="gist"]');
      // Use a valid hex gist ID so parseGistUrl succeeds and the fetch is initiated
      await gistInput.fill('https://gist.github.com/user/abc123def456');

      const loadButton = page.getByRole('button', { name: 'load gist' });
      await loadButton.click();

      // The button should show a spinner (animate-spin class on the SVG)
      const loadingIndicator = page.locator('.animate-spin').first();
      await expect(loadingIndicator).toBeVisible({ timeout: 2000 });
    });

    test('disables the input and button while loading', async ({ page }) => {
      // Intercept the GitHub API request and delay it to observe loading state
      await page.route('**/api.github.com/**', async route => {
        await new Promise(r => setTimeout(r, 3000));
        await route.fulfill({ status: 404, body: 'Not found' });
      });

      const gistInput = page.locator('input[placeholder*="gist"]');
      // Use a valid hex gist ID so parseGistUrl succeeds and the fetch is initiated
      await gistInput.fill('https://gist.github.com/user/abc123def456');

      const loadButton = page.getByRole('button', { name: 'load gist' });
      await loadButton.click();

      // During loading, the UploadZone is replaced by a loading overlay
      // The gist input is removed from the DOM and the loading message is shown
      await expect(page.getByText('loading session from gist...')).toBeVisible({
        timeout: 2000,
      });

      // After loading completes (route responds after 3s), the input should reappear
      await expect(gistInput).toBeVisible({ timeout: 10_000 });
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
