/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/web/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import { expect, test } from '@playwright/test';
import { loadSample } from './helpers.js';

test.describe('Message Filtering', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    await loadSample(page, 'Claude Code');
  });

  test.describe('Text filter', () => {
    test('filters messages by content when text is entered in the filter bar', async ({
      page,
    }) => {
      const filterInput = page.locator('input[placeholder*="filter"]');
      await filterInput.fill('explore');

      // Wait for filter to apply
      await page.waitForTimeout(300);

      // Filtered view should show fewer entries or matching entries
      const visibleEntries = page.locator(
        'main .flex-1 .overflow-y-auto > div > div'
      );
      const count = await visibleEntries.count();
      expect(count).toBeGreaterThan(0);
    });

    test('filters assistant messages by content', async ({ page }) => {
      const filterInput = page.locator('input[placeholder*="filter"]');
      // Use a term likely to appear in assistant messages
      await filterInput.fill('capsule');
      await page.waitForTimeout(300);

      const visibleEntries = page.locator(
        'main .flex-1 .overflow-y-auto > div > div'
      );
      const count = await visibleEntries.count();
      expect(count).toBeGreaterThan(0);
    });

    test('filters tool call entries by tool name', async ({ page }) => {
      const filterInput = page.locator('input[placeholder*="filter"]');
      // Search for a tool name that exists in the Claude sample
      await filterInput.fill('Glob');
      await page.waitForTimeout(300);

      // Should still see some tool call entries matching "Glob"
      const toolCalls = page.locator('main').getByText('tool_call');
      // Either matching entries are visible, or the timeline is filtered
    });

    test('filters tool call entries by result content', async ({ page }) => {
      const filterInput = page.locator('input[placeholder*="filter"]');
      // Search for content that would appear in tool results
      await filterInput.fill('output');
      await page.waitForTimeout(300);

      const visibleEntries = page.locator(
        'main .flex-1 .overflow-y-auto > div > div'
      );
      const count = await visibleEntries.count();
      expect(count).toBeGreaterThan(0);
    });

    test('filters subagent entries by description', async ({ page }) => {
      const filterInput = page.locator('input[placeholder*="filter"]');
      // Search for "subagent" which should match subagent description fields
      await filterInput.fill('subagent');
      await page.waitForTimeout(300);

      const visibleEntries = page.locator(
        'main .flex-1 .overflow-y-auto > div > div'
      );
      const count = await visibleEntries.count();
      expect(count).toBeGreaterThan(0);
    });

    test('shows all entries when the filter is cleared', async ({ page }) => {
      const filterInput = page.locator('input[placeholder*="filter"]');

      // Count entries before filtering
      await page.waitForTimeout(500);
      const beforeGroups = page.locator(
        'main .flex-1 .overflow-y-auto > div > div:not([aria-hidden])'
      );
      const beforeCount = await beforeGroups.count();

      // Filter to reduce entries
      await filterInput.fill('xyznonexistent');
      await page.waitForTimeout(300);

      // Clear filter
      await filterInput.fill('');
      await page.waitForTimeout(300);

      // Should restore all entries
      const afterCount = await beforeGroups.count();
      expect(afterCount).toBe(beforeCount);
    });

    test('the filter is case-insensitive', async ({ page }) => {
      const filterInput = page.locator('input[placeholder*="filter"]');

      // Filter with lowercase
      await filterInput.fill('capsule');
      await page.waitForTimeout(300);
      const lcGroups = page.locator(
        'main .flex-1 .overflow-y-auto > div > div:not([aria-hidden])'
      );
      const lcCount = await lcGroups.count();

      // Filter with uppercase
      await filterInput.fill('CAPSULE');
      await page.waitForTimeout(300);
      const ucCount = await lcGroups.count();

      expect(lcCount).toBe(ucCount);
    });
  });

  test.describe('Empty results', () => {
    test('shows an empty timeline when no entries match the filter', async ({
      page,
    }) => {
      const filterInput = page.locator('input[placeholder*="filter"]');
      await filterInput.fill('xyzabsolutelynomatchzyx');
      await page.waitForTimeout(300);

      // The timeline should show the end-of-session marker but no message entries
      // The only visible content should be the end marker
      const userLabels = page.locator(
        'main .overflow-y-auto span:has-text("user"):not([aria-hidden])'
      );
      // When no entries match, there shouldn't be user/agent labels in the message area
      // (The filter bar itself might contain "user" text, so we look specifically in the thread)
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
