/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/web/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import { expect, test } from '@playwright/test';
import {
  loadSample,
  waitForSessionInSidebar,
  waitForTimeline,
} from './helpers.js';

test.describe('Sample Loading', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test.describe('Load Claude Code sample', () => {
    test('loads the Claude Code sample when the button is clicked', async ({
      page,
    }) => {
      await loadSample(page, 'Claude Code');
    });

    test('adds the sample session to the sidebar list', async ({ page }) => {
      await loadSample(page, 'Claude Code');
      const sidebar = page.locator('aside');
      await expect(sidebar.getByText('[1]')).toBeVisible();
    });

    test('opens the session in a tab and displays its timeline', async ({
      page,
    }) => {
      await loadSample(page, 'Claude Code');
      await expect(
        page.locator('main').getByText('user').first()
      ).toBeVisible();
      await expect(
        page.locator('main').getByText('agent').first()
      ).toBeVisible();
    });

    test('the session format is detected as claude', async ({ page }) => {
      await loadSample(page, 'Claude Code');
      // The sidebar should show the format label
      await expect(
        page.locator('aside').getByText('claude').first()
      ).toBeVisible();
    });
  });

  test.describe('Load Codex sample', () => {
    test('loads the Codex sample when the button is clicked', async ({
      page,
    }) => {
      await loadSample(page, 'Codex');
    });

    test('adds the sample session to the sidebar list', async ({ page }) => {
      await loadSample(page, 'Codex');
      const sidebar = page.locator('aside');
      await expect(sidebar.getByText('[1]')).toBeVisible();
    });

    test('opens the session in a tab and displays its timeline', async ({
      page,
    }) => {
      await loadSample(page, 'Codex');
      await expect(
        page.locator('main').getByText('user').first()
      ).toBeVisible();
      await expect(
        page.locator('main').getByText('agent').first()
      ).toBeVisible();
    });

    test('the session format is detected as codex', async ({ page }) => {
      await loadSample(page, 'Codex');
      await expect(
        page.locator('aside').getByText('codex').first()
      ).toBeVisible();
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
