/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/web/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import { expect, test } from '@playwright/test';
import { loadSample } from './helpers.js';

test.describe('Session Deletion', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    await loadSample(page, 'Claude Code');
  });

  test.describe('Delete from session panel', () => {
    test('shows a confirmation dialog when the delete button is clicked', async ({
      page,
    }) => {
      const panel = page.locator('aside').last();
      const deleteButton = panel.getByTitle('Delete session');
      await deleteButton.click();

      // Confirmation modal should appear — use the dialog role
      const dialog = page.locator('div[role="dialog"]');
      await expect(dialog).toBeVisible();
      await expect(dialog.getByText('Are you sure')).toBeVisible();
    });

    test('removes the session from the sidebar list after confirmation', async ({
      page,
    }) => {
      const panel = page.locator('aside').last();
      const deleteButton = panel.getByTitle('Delete session');
      await deleteButton.click();

      // Click the confirm button inside the dialog
      const dialog = page.locator('div[role="dialog"]');
      await dialog.locator('button.bg-red-600').click();

      // Session should be removed from sidebar
      const sidebar = page.locator('aside').first();
      await expect(sidebar.getByText('[0]')).toBeVisible();
    });

    test('closes all tabs displaying the deleted session', async ({ page }) => {
      const panel = page.locator('aside').last();
      const deleteButton = panel.getByTitle('Delete session');
      await deleteButton.click();

      const dialog = page.locator('div[role="dialog"]');
      await dialog.locator('button.bg-red-600').click();

      // After deletion, should show the upload zone (empty state)
      await expect(
        page.locator('main').getByText('upload --session')
      ).toBeVisible();
    });

    test('does not delete the session when the confirmation is cancelled', async ({
      page,
    }) => {
      const panel = page.locator('aside').last();
      const deleteButton = panel.getByTitle('Delete session');
      await deleteButton.click();

      // Click "Cancel" inside the dialog
      const dialog = page.locator('div[role="dialog"]');
      await dialog.getByText('Cancel').click();

      // Session should still be in sidebar
      const sidebar = page.locator('aside').first();
      await expect(sidebar.getByText('[1]')).toBeVisible();
    });
  });

  test.describe('Session list cleanup', () => {
    test('removes the session from browser storage after deletion', async ({
      page,
    }) => {
      const panel = page.locator('aside').last();
      const deleteButton = panel.getByTitle('Delete session');
      await deleteButton.click();

      const dialog = page.locator('div[role="dialog"]');
      await dialog.locator('button.bg-red-600').click();

      // Reload the page — session should not reappear
      await page.reload();
      const sidebar = page.locator('aside').first();
      await expect(sidebar.getByText('[0]')).toBeVisible();
    });

    test('updates the session count in the sidebar', async ({ page }) => {
      // Load a second sample
      await page.getByRole('button', { name: '+' }).click();
      await page.getByRole('button', { name: 'Codex', exact: true }).click();
      await page.waitForTimeout(1000);

      // Count should be 2
      const sidebar = page.locator('aside').first();
      await expect(sidebar.getByText('[2]')).toBeVisible();

      // Click first session in sidebar to ensure we're viewing it
      const sessionItem = sidebar.locator('button:has-text("steps")').first();
      await sessionItem.click();
      await page.waitForTimeout(500);

      const panel = page.locator('aside').last();
      const deleteButton = panel.getByTitle('Delete session');
      await deleteButton.click();

      // Click confirm inside dialog
      const dialog = page.locator('div[role="dialog"]');
      await dialog.locator('button.bg-red-600').click();

      // Count should be 1
      await expect(sidebar.getByText('[1]')).toBeVisible();
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
