/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/web/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import { expect, test } from '@playwright/test';
import { loadSample } from './helpers.js';

test.describe('Session Panel', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    await loadSample(page, 'Claude Code');
  });

  test.describe('Session info display', () => {
    test('displays the session file name in the panel header', async ({
      page,
    }) => {
      const panel = page.locator('aside').last();
      // The panel header shows the session name followed by "/"
      await expect(panel.locator('.font-medium').first()).toBeVisible();
    });

    test('displays the step count', async ({ page }) => {
      const panel = page.locator('aside').last();
      await expect(panel.getByText('steps')).toBeVisible();
    });

    test('shows the agent name when available', async ({ page }) => {
      const panel = page.locator('aside').last();
      await expect(panel.getByText('agent')).toBeVisible();
    });

    test('shows the model name when available', async ({ page }) => {
      const panel = page.locator('aside').last();
      await expect(panel.getByText('model')).toBeVisible();
    });

    test('shows the working directory when available', async ({ page }) => {
      const panel = page.locator('aside').last();
      await expect(panel.getByText('directory')).toBeVisible();
    });

    test('shows the git branch when available', async ({ page }) => {
      const panel = page.locator('aside').last();
      await expect(panel.getByText('branch')).toBeVisible();
    });
  });

  test.describe('Token statistics', () => {
    test('displays the total token usage when available', async ({ page }) => {
      const panel = page.locator('aside').last();
      // The token stats section has "// tokens_and_cost" header
      await expect(panel.getByText('tokens_and_cost')).toBeVisible();
    });

    test('shows input and output token breakdowns when available', async ({
      page,
    }) => {
      const panel = page.locator('aside').last();
      await expect(panel.getByText('input tokens')).toBeVisible();
      await expect(panel.getByText('output tokens')).toBeVisible();
    });
  });

  test.describe('File list', () => {
    test('lists files that were read during the session', async ({ page }) => {
      const panel = page.locator('aside').last();
      // The files section has "// files" header
      const filesSection = panel.getByText('// files');
      if (await filesSection.isVisible()) {
        await expect(panel.getByText('read').first()).toBeVisible();
      }
    });

    test('lists files that were edited during the session', async ({
      page,
    }) => {
      const panel = page.locator('aside').last();
      const filesSection = panel.getByText('// files');
      if (await filesSection.isVisible()) {
        // May or may not have edited files depending on the sample
        const edited = panel.getByText('edited');
        if (await edited.isVisible()) {
          await expect(edited).toBeVisible();
        }
      }
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
