/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/web/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import { expect, test } from '@playwright/test';
import {
  uploadFixture,
  waitForSessionInSidebar,
  waitForTimeline,
} from './helpers.js';

test.describe('Session Upload', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test.describe('File picker upload', () => {
    test('accepts .jsonl files and stores the session', async ({ page }) => {
      await uploadFixture(page, 'claude-session.jsonl');
      await waitForSessionInSidebar(page);
    });

    test('accepts .json files and stores the session', async ({ page }) => {
      const fileInput = page.locator('input[type="file"]').first();
      await fileInput.setInputFiles({
        name: 'test-session.json',
        mimeType: 'application/json',
        buffer: Buffer.from(
          JSON.stringify({
            projectHash: 'abc123',
            sessionId: 'gemini-test',
            startTime: '2026-01-01T10:00:00.000Z',
            messages: [
              {
                role: 'user',
                content: 'Hello',
                timestamp: '2026-01-01T10:00:01.000Z',
              },
              {
                role: 'model',
                content: 'Hi!',
                timestamp: '2026-01-01T10:00:02.000Z',
              },
            ],
          })
        ),
      });
      await waitForSessionInSidebar(page);
    });

    test('adds the uploaded session to the sidebar session list', async ({
      page,
    }) => {
      await uploadFixture(page, 'claude-session.jsonl');
      await waitForSessionInSidebar(page);

      const sidebar = page.locator('aside');
      await expect(sidebar.getByText('[1]')).toBeVisible();
    });

    test('opens the uploaded session in a new tab automatically', async ({
      page,
    }) => {
      await uploadFixture(page, 'claude-session.jsonl');
      await waitForSessionInSidebar(page);

      const tabBar = page.locator('main > div').first();
      await expect(tabBar.locator('button').first()).toBeVisible();
    });

    test('parses the session and displays the timeline in the message thread', async ({
      page,
    }) => {
      await uploadFixture(page, 'claude-session.jsonl');
      await waitForTimeline(page);

      await expect(
        page.locator('main').getByText('user').first()
      ).toBeVisible();
      await expect(
        page.locator('main').getByText('agent').first()
      ).toBeVisible();
    });
  });

  test.describe('Drag-and-drop upload', () => {
    test('accepts a .jsonl file dropped onto the upload zone', async ({
      page,
    }) => {
      await uploadFixture(page, 'claude-session.jsonl');
      await waitForSessionInSidebar(page);
    });

    test('accepts a .json file dropped onto the upload zone', async ({
      page,
    }) => {
      // Use the main content's file input (inside the upload zone)
      const fileInput = page.locator('main input[type="file"]').first();
      await fileInput.setInputFiles({
        name: 'gemini.json',
        mimeType: 'application/json',
        buffer: Buffer.from(
          JSON.stringify({
            projectHash: 'abc123',
            sessionId: 'gemini-test',
            startTime: '2026-01-01T10:00:00.000Z',
            messages: [
              {
                role: 'user',
                content: 'Hello',
                timestamp: '2026-01-01T10:00:01.000Z',
              },
              {
                role: 'model',
                content: 'Hi!',
                timestamp: '2026-01-01T10:00:02.000Z',
              },
            ],
          })
        ),
      });
      await waitForSessionInSidebar(page);
    });

    test('ignores files with unsupported extensions', async ({ page }) => {
      // Simulate dropping a .txt file onto the upload zone.
      // The drop handler only processes .jsonl and .json files.
      const uploadZone = page.locator('div.border-dashed').first();
      await uploadZone.evaluate(el => {
        const file = new File(['this is plain text'], 'unsupported.txt', {
          type: 'text/plain',
        });
        const dt = new DataTransfer();
        dt.items.add(file);
        el.dispatchEvent(
          new DragEvent('drop', { dataTransfer: dt, bubbles: true })
        );
      });

      // Wait briefly and verify no session was added
      await page.waitForTimeout(1000);
      const sidebar = page.locator('aside');
      await expect(sidebar.locator('text=/\\[0\\]/')).toBeVisible();
    });

    test('shows a visual drag-over indicator when a file is dragged over the upload zone', async ({
      page,
    }) => {
      const uploadZone = page.locator('div.border-dashed').first();
      // Dispatch dragenter to increment the drag counter
      await uploadZone.dispatchEvent('dragenter');
      // The zone should gain the accent border styling
      // Check for the CSS class change (isDragging adds border-accent)
      await expect(uploadZone).toHaveClass(/border-accent/);
    });
  });

  test.describe('Multiple session uploads', () => {
    test('allows uploading multiple sessions sequentially', async ({
      page,
    }) => {
      // Upload first session via sidebar file input
      await uploadFixture(page, 'claude-session.jsonl');
      await waitForSessionInSidebar(page);

      // Open a new tab for the second upload
      await page.getByRole('button', { name: '+' }).click();

      // Upload second session via the main upload zone input
      const mainInput = page.locator('main input[type="file"]').first();
      await mainInput.setInputFiles({
        name: 'codex-session.jsonl',
        mimeType: 'application/jsonl',
        buffer: Buffer.from(
          '{"type":"session_meta","session_id":"codex-test","originator":"codex","started_at":"2026-01-01T10:00:00.000Z","cwd":"/tmp"}\n{"type":"event_msg","event":{"role":"user","content":"Hello"},"timestamp":"2026-01-01T10:00:01.000Z"}\n'
        ),
      });

      // Wait for second session to appear
      await page.waitForTimeout(500);

      // Both sessions should be in sidebar
      const sidebar = page.locator('aside');
      await expect(sidebar.getByText('[2]')).toBeVisible();
    });

    test('each uploaded session opens in its own tab', async ({ page }) => {
      // Upload first session
      await uploadFixture(page, 'claude-session.jsonl');
      await waitForSessionInSidebar(page);

      // Open a new tab and upload a second session
      await page.getByRole('button', { name: '+' }).click();
      const mainInput = page.locator('main input[type="file"]').first();
      await mainInput.setInputFiles({
        name: 'codex-session.jsonl',
        mimeType: 'application/jsonl',
        buffer: Buffer.from(
          '{"type":"session_meta","session_id":"codex-test","originator":"codex","started_at":"2026-01-01T10:00:00.000Z","cwd":"/tmp"}\n{"type":"event_msg","event":{"role":"user","content":"Hello"},"timestamp":"2026-01-01T10:00:01.000Z"}\n'
        ),
      });

      await page.waitForTimeout(500);

      // Both tabs should exist in the tab bar
      const tabBar = page.locator('main > div').first();
      const tabs = tabBar.locator('button:not(:has-text("+"))');
      const tabCount = await tabs.count();
      expect(tabCount).toBeGreaterThanOrEqual(2);
    });

    test('displays all uploaded sessions in the sidebar list', async ({
      page,
    }) => {
      await uploadFixture(page, 'claude-session.jsonl');
      await waitForSessionInSidebar(page);

      await page.getByRole('button', { name: '+' }).click();

      const mainInput = page.locator('main input[type="file"]').first();
      await mainInput.setInputFiles({
        name: 'second.jsonl',
        mimeType: 'application/jsonl',
        buffer: Buffer.from(
          '{"parentUuid":null,"isSidechain":false,"userType":"external","cwd":"/tmp","sessionId":"sess-2","version":"2.1.0","type":"user","message":{"role":"user","content":"Test"},"uuid":"m1","timestamp":"2026-01-01T10:00:00.000Z"}\n'
        ),
      });

      await page.waitForTimeout(500);

      const sidebar = page.locator('aside');
      await expect(sidebar.getByText('[2]')).toBeVisible();
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
