/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/web/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import { expect, test } from '@playwright/test';
import {
  loadSample,
  uploadFixture,
  waitForSessionInSidebar,
  waitForTimeline,
} from './helpers.js';

test.describe('Tab Management', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test.describe('Tab creation', () => {
    test('opens a new empty tab when the "+" button is clicked', async ({
      page,
    }) => {
      await loadSample(page, 'Claude Code');

      // Click the "+" button
      await page.getByRole('button', { name: '+' }).click();

      // The upload zone should be visible in the new empty tab
      await expect(
        page.locator('main').getByText('upload --session')
      ).toBeVisible();
    });

    test('opens a new tab with a session when a session is selected from the sidebar', async ({
      page,
    }) => {
      await loadSample(page, 'Claude Code');

      // Open a new tab
      await page.getByRole('button', { name: '+' }).click();

      // Load a second sample (Codex) in the new tab
      await page.getByRole('button', { name: 'Codex' }).click();
      await waitForTimeline(page);

      // Both tabs should be visible
      const tabBar = page.locator('main > div').first();
      const tabs = tabBar.locator('button').filter({ hasNotText: '+' });
      // Should have at least 2 tabs (claude + codex)
      await expect(tabs.first()).toBeVisible();
    });

    test('displays the session name as the tab label', async ({ page }) => {
      await loadSample(page, 'Claude Code');

      // Tab should contain part of the session name
      const tabBar = page.locator('main > div').first();
      // The tab label should be visible (it truncates but shows the name)
      await expect(
        tabBar.locator('button span.truncate').first()
      ).toBeVisible();
    });
  });

  test.describe('Tab switching', () => {
    test('switches the displayed session when a different tab is clicked', async ({
      page,
    }) => {
      // Load Claude sample
      await loadSample(page, 'Claude Code');

      // Open new tab and load Codex
      await page.getByRole('button', { name: '+' }).click();
      await page.getByRole('button', { name: 'Codex' }).click();
      await waitForTimeline(page);

      // Click back to the first tab
      const tabBar = page.locator('main > div').first();
      const firstTab = tabBar.locator('button').first();
      await firstTab.click();

      // Should show the Claude session timeline
      await expect(
        page.locator('main').getByText('agent').first()
      ).toBeVisible();
    });

    test('shows the upload zone when an empty tab is active', async ({
      page,
    }) => {
      await loadSample(page, 'Claude Code');
      await page.getByRole('button', { name: '+' }).click();
      await expect(
        page.locator('main').getByText('upload --session')
      ).toBeVisible();
    });

    test('highlights the active tab visually', async ({ page }) => {
      await loadSample(page, 'Claude Code');

      // The active tab should have a different styling (bg-surface class)
      const tabBar = page.locator('main > div').first();
      const activeTab = tabBar.locator('button.bg-surface').first();
      await expect(activeTab).toBeVisible();
    });
  });

  test.describe('Tab closing', () => {
    test('closes a tab when its close button is clicked', async ({ page }) => {
      await loadSample(page, 'Claude Code');

      // Open a new tab
      await page.getByRole('button', { name: '+' }).click();

      // Close the new tab (hover over it to reveal close button, then click)
      const tabBar = page.locator('main > div').first();
      const tabs = tabBar.locator('button:not(:has-text("+"))');
      const lastTab = tabs.last();
      await lastTab.hover();

      // Click the close button (× character)
      const closeButton = lastTab.getByTitle('Close tab');
      await closeButton.click();

      // Should still show the first tab
      await expect(
        page.locator('main').getByText('agent').first()
      ).toBeVisible();
    });

    test('activates the nearest remaining tab after closing', async ({
      page,
    }) => {
      // Load first session
      await loadSample(page, 'Claude Code');

      // Open a new tab and load second session
      await page.getByRole('button', { name: '+' }).click();
      await page.getByRole('button', { name: 'Codex' }).click();
      await waitForTimeline(page);

      // Close the second (active) tab
      const tabBar = page.locator('main > div').first();
      const activeTab = tabBar.locator('button:not(:has-text("+"))').last();
      await activeTab.hover();
      const closeButton = activeTab.getByTitle('Close tab');
      await closeButton.click();

      // The first tab should now be active and show its session
      await expect(
        page.locator('main').getByText('agent').first()
      ).toBeVisible();
    });

    test('does not remove the session from the sidebar when its tab is closed', async ({
      page,
    }) => {
      await loadSample(page, 'Claude Code');

      // Open a new tab
      await page.getByRole('button', { name: '+' }).click();

      // Count tabs
      const tabBar = page.locator('main > div').first();

      // Go back to first tab and hover to close
      const firstTab = tabBar.locator('button:not(:has-text("+"))').first();
      await firstTab.click();

      // The session should still be in the sidebar
      await expect(page.locator('aside').getByText('[1]')).toBeVisible();
    });
  });

  test.describe('Duplicate prevention', () => {
    test('focuses the existing tab when selecting a session already open', async ({
      page,
    }) => {
      await loadSample(page, 'Claude Code');

      // Open a new empty tab
      await page.getByRole('button', { name: '+' }).click();

      // Click the Claude session in the sidebar
      const sidebarSession = page
        .locator('aside button:has-text("steps")')
        .first();
      await sidebarSession.click();

      // It should focus the existing tab, not create a new one
      // The session viewer should be visible (not the upload zone)
      await expect(
        page.locator('main').getByText('agent').first()
      ).toBeVisible();
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
