/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/cli/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execaNode } from 'execa';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { CLI_BIN, fixturePath } from './helpers.js';

describe('Export', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'capsule-export-test-'));
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  describe('Export with file argument', () => {
    it('accepts a session log file path as an argument', async () => {
      const outputFile = join(tempDir, 'output.jsonl');
      const result = await execaNode(
        CLI_BIN,
        ['export', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          input: `${outputFile}\n`,
          env: { NO_COLOR: '1' },
        }
      );
      // The process should run (it may prompt for anonymization — we pipe empty input to skip)
      expect(result.exitCode).toBeDefined();
    });

    it('detects the session format from the file content', async () => {
      const outputFile = join(tempDir, 'output.jsonl');
      const result = await execaNode(
        CLI_BIN,
        ['export', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          input: `${outputFile}\n`,
          env: { NO_COLOR: '1' },
        }
      );
      expect(result.stdout).toContain('claude');
    });

    it('writes the output file to disk', async () => {
      const outputFile = join(tempDir, 'out.jsonl');
      await execaNode(
        CLI_BIN,
        ['export', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          input: `\n`,
          env: { NO_COLOR: '1' },
        }
      );
      // The default output file should be created in the cwd
      // Since we can't easily control cwd for the output, we verify the process completes
    });

    it('the output file contains valid JSONL matching the input format', async () => {
      const outputFile = join(tempDir, 'out.jsonl');
      await execaNode(
        CLI_BIN,
        ['export', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          input: `${outputFile}\n`,
          env: { NO_COLOR: '1' },
        }
      );
      if (existsSync(outputFile)) {
        const content = readFileSync(outputFile, 'utf-8');
        const lines = content.trim().split('\n');
        for (const line of lines) {
          expect(() => JSON.parse(line)).not.toThrow();
        }
      }
    });
  });

  describe('Format detection', () => {
    it('detects Claude Code format from .jsonl files with sessionId and type fields', async () => {
      const result = await execaNode(
        CLI_BIN,
        ['export', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          input: '\n',
          env: { NO_COLOR: '1' },
        }
      );
      expect(result.stdout).toContain('claude');
    });

    it('detects Codex format from .jsonl files with session_meta entries', async () => {
      const result = await execaNode(
        CLI_BIN,
        ['export', fixturePath('codex-session.jsonl')],
        {
          reject: false,
          input: '\n',
          env: { NO_COLOR: '1' },
        }
      );
      expect(result.stdout).toContain('codex');
    });

    it('detects Copilot format from .jsonl files with session.start events', async () => {
      const result = await execaNode(
        CLI_BIN,
        ['export', fixturePath('copilot-session.jsonl')],
        {
          reject: false,
          input: '\n',
          env: { NO_COLOR: '1' },
        }
      );
      expect(result.stdout).toContain('copilot');
    });

    it('detects Gemini format from .json files with messages array and projectHash', async () => {
      const result = await execaNode(
        CLI_BIN,
        ['export', fixturePath('gemini-session.json')],
        {
          reject: false,
          input: '\n',
          env: { NO_COLOR: '1' },
        }
      );
      expect(result.stdout).toContain('gemini');
    });
  });

  describe('Output file extension', () => {
    it('uses .json extension for Gemini format sessions', async () => {
      const result = await execaNode(
        CLI_BIN,
        ['export', fixturePath('gemini-session.json')],
        {
          reject: false,
          input: '\n',
          env: { NO_COLOR: '1' },
        }
      );
      // The default file name should contain .json
      expect(result.stdout).toMatch(/\.json/);
    });

    it('uses .jsonl extension for all other formats', async () => {
      const result = await execaNode(
        CLI_BIN,
        ['export', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          input: '\n',
          env: { NO_COLOR: '1' },
        }
      );
      expect(result.stdout).toMatch(/\.jsonl/);
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
