/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/cli/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import { execaNode } from 'execa';
import { describe, expect, it } from 'vitest';
import { CLI_BIN } from './helpers.js';

describe('Help and Usage', () => {
  describe('Default help output', () => {
    it('prints usage text including share, export, and serve subcommands when run with no arguments', async () => {
      const result = await execaNode(CLI_BIN, [], { reject: false });
      expect(result.stdout).toContain('share');
      expect(result.stdout).toContain('export');
      expect(result.stdout).toContain('serve');
    });

    it('exits with code 0', async () => {
      const result = await execaNode(CLI_BIN, [], { reject: false });
      expect(result.exitCode).toBe(0);
    });
  });

  describe('--help flag', () => {
    it('prints the same usage text when run with --help', async () => {
      const result = await execaNode(CLI_BIN, ['--help'], { reject: false });
      expect(result.stdout).toContain('share');
      expect(result.stdout).toContain('export');
      expect(result.stdout).toContain('serve');
    });

    it('exits with code 0', async () => {
      const result = await execaNode(CLI_BIN, ['--help'], { reject: false });
      expect(result.exitCode).toBe(0);
    });
  });

  describe('-h short flag', () => {
    it('prints the same usage text when run with -h', async () => {
      const result = await execaNode(CLI_BIN, ['-h'], { reject: false });
      expect(result.stdout).toContain('share');
      expect(result.stdout).toContain('export');
      expect(result.stdout).toContain('serve');
    });

    it('exits with code 0', async () => {
      const result = await execaNode(CLI_BIN, ['-h'], { reject: false });
      expect(result.exitCode).toBe(0);
    });
  });

  describe('Unknown command', () => {
    it('prints an error message containing the unknown command name', async () => {
      const result = await execaNode(CLI_BIN, ['foobar'], { reject: false });
      expect(result.stderr).toContain('foobar');
    });

    it('prints the usage text after the error', async () => {
      const result = await execaNode(CLI_BIN, ['foobar'], { reject: false });
      expect(result.stdout).toContain('share');
      expect(result.stdout).toContain('export');
      expect(result.stdout).toContain('serve');
    });

    it('exits with a non-zero exit code', async () => {
      const result = await execaNode(CLI_BIN, ['foobar'], { reject: false });
      expect(result.exitCode).not.toBe(0);
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
