/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/cli/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import { execaNode } from 'execa';
import { afterEach, describe, expect, it } from 'vitest';
import { CLI_BIN } from './helpers.js';

describe('Serve', () => {
  let proc: ReturnType<typeof execaNode> | null = null;

  afterEach(() => {
    if (proc) {
      proc.kill('SIGTERM');
      proc = null;
    }
  });

  async function waitForServer(
    port: number,
    timeoutMs = 15_000
  ): Promise<void> {
    const start = Date.now();
    while (Date.now() - start < timeoutMs) {
      try {
        const res = await fetch(`http://127.0.0.1:${port}`);
        if (res.ok || res.status < 500) return;
      } catch {
        // not ready yet
      }
      await new Promise(r => setTimeout(r, 200));
    }
    throw new Error(
      `Server did not start on port ${port} within ${timeoutMs}ms`
    );
  }

  describe('Default port', () => {
    it('starts an HTTP server on port 3123 by default', async () => {
      proc = execaNode(CLI_BIN, ['serve'], { reject: false });
      await waitForServer(3123);
    });

    it('responds to HTTP requests on http://127.0.0.1:3123', async () => {
      proc = execaNode(CLI_BIN, ['serve'], { reject: false });
      await waitForServer(3123);

      const res = await fetch('http://127.0.0.1:3123');
      expect(res.ok).toBe(true);
    });

    it('serves the web app HTML page at the root URL', async () => {
      proc = execaNode(CLI_BIN, ['serve'], { reject: false });
      await waitForServer(3123);

      const res = await fetch('http://127.0.0.1:3123');
      const text = await res.text();
      expect(text).toContain('<!');
      expect(res.headers.get('content-type')).toContain('text/html');
    });

    it('exits cleanly when receiving SIGTERM', async () => {
      proc = execaNode(CLI_BIN, ['serve'], { reject: false });
      await waitForServer(3123);

      proc.kill('SIGTERM');
      const result = await proc;
      proc = null;
      // After SIGTERM the process should have exited
      expect(result.exitCode).toBeDefined();
    });
  });

  describe('Custom port', () => {
    it('accepts --port <number> to override the default port', async () => {
      proc = execaNode(CLI_BIN, ['serve', '--port', '4567'], {
        reject: false,
      });
      await waitForServer(4567);
    });

    it('responds to requests on the custom port', async () => {
      proc = execaNode(CLI_BIN, ['serve', '--port', '4568'], {
        reject: false,
      });
      await waitForServer(4568);

      const res = await fetch('http://127.0.0.1:4568');
      expect(res.ok).toBe(true);
    });
  });

  describe('Port validation', () => {
    it('ignores invalid port values and falls back to the default port', async () => {
      proc = execaNode(CLI_BIN, ['serve', '--port', 'abc'], {
        reject: false,
      });
      await waitForServer(3123);

      const res = await fetch('http://127.0.0.1:3123');
      expect(res.ok).toBe(true);
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
