/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * To modify these tests, update the specification files:
 * - packages/cli/E2E_TESTS.md
 *
 * Then run the houston-update command to regenerate this file.
 * ============================================================================
 */

import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execaNode } from 'execa';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { CLI_BIN, fixturePath } from './helpers.js';

describe('Share', () => {
  let tempDir: string;
  let mockBinDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'capsule-share-test-'));
    mockBinDir = join(tempDir, 'bin');
    mkdirSync(mockBinDir, { recursive: true });
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  function createMockGh(
    authExitCode: number,
    gistOutput = 'https://gist.github.com/user/abc123'
  ): string {
    const ghScript = join(mockBinDir, 'gh');
    const script = `#!/bin/sh
if [ "$1" = "auth" ] && [ "$2" = "status" ]; then
  exit ${authExitCode}
fi
if [ "$1" = "gist" ] && [ "$2" = "create" ]; then
  echo "${gistOutput}"
  exit 0
fi
exit 1
`;
    writeFileSync(ghScript, script, 'utf-8');
    chmodSync(ghScript, 0o755);
    return mockBinDir;
  }

  /**
   * Send keystrokes to navigate through clack prompts:
   * 1. Multiselect (anonymization): Enter to submit with no selections
   * 2. Select (visibility): Enter to pick first option (secret)
   */
  async function sendPromptInputs(
    proc: ReturnType<typeof execaNode>
  ): Promise<void> {
    const stdin = proc.stdin;
    if (!stdin) return;

    // Wait for the multiselect prompt to render, then press Enter (no selections)
    await new Promise(r => setTimeout(r, 500));
    stdin.write('\r');

    // Wait for the select prompt to render, then press Enter (first option)
    await new Promise(r => setTimeout(r, 500));
    stdin.write('\r');

    // End stdin so the process can finish
    await new Promise(r => setTimeout(r, 200));
    stdin.end();
  }

  describe('Authentication check', () => {
    it('checks gh authentication status before proceeding', async () => {
      const binDir = createMockGh(0);
      const proc = execaNode(
        CLI_BIN,
        ['share', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          env: {
            NO_COLOR: '1',
            PATH: `${binDir}:${process.env.PATH}`,
          },
        }
      );
      sendPromptInputs(proc);
      const result = await proc;
      // Should have proceeded past auth check (exit 0 from mock)
      expect(result.exitCode).toBeDefined();
    });

    it('fails with an error message when gh auth status returns a non-zero exit code', async () => {
      const binDir = createMockGh(1);
      const result = await execaNode(
        CLI_BIN,
        ['share', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          env: {
            NO_COLOR: '1',
            PATH: `${binDir}:${process.env.PATH}`,
          },
        }
      );
      expect(result.stdout + result.stderr).toMatch(/auth/i);
    });

    it('exits with a non-zero exit code when authentication fails', async () => {
      const binDir = createMockGh(1);
      const result = await execaNode(
        CLI_BIN,
        ['share', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          env: {
            NO_COLOR: '1',
            PATH: `${binDir}:${process.env.PATH}`,
          },
        }
      );
      expect(result.exitCode).not.toBe(0);
    });
  });

  describe('Gist creation with mock gh', () => {
    it('calls gh gist create when authentication succeeds', async () => {
      const logFile = join(tempDir, 'gh-log.txt');
      const ghScript = join(mockBinDir, 'gh');
      const script = `#!/bin/sh
echo "$@" >> "${logFile}"
if [ "$1" = "auth" ] && [ "$2" = "status" ]; then
  exit 0
fi
if [ "$1" = "gist" ] && [ "$2" = "create" ]; then
  echo "https://gist.github.com/user/abc123"
  exit 0
fi
exit 1
`;
      writeFileSync(ghScript, script, 'utf-8');
      chmodSync(ghScript, 0o755);

      const proc = execaNode(
        CLI_BIN,
        ['share', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          env: {
            NO_COLOR: '1',
            PATH: `${mockBinDir}:${process.env.PATH}`,
          },
        }
      );
      sendPromptInputs(proc);
      await proc;

      if (existsSync(logFile)) {
        const log = readFileSync(logFile, 'utf-8');
        expect(log).toContain('gist create');
      }
    });

    it('reports the Gist URL on success', async () => {
      const binDir = createMockGh(0, 'https://gist.github.com/user/abc123');
      const proc = execaNode(
        CLI_BIN,
        ['share', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          env: {
            NO_COLOR: '1',
            PATH: `${binDir}:${process.env.PATH}`,
          },
        }
      );
      sendPromptInputs(proc);
      const result = await proc;
      expect(result.stdout).toContain('gist.github.com');
    });

    it('reports the viewer URL on success', async () => {
      const binDir = createMockGh(0, 'https://gist.github.com/user/abc123');
      const proc = execaNode(
        CLI_BIN,
        ['share', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          env: {
            NO_COLOR: '1',
            PATH: `${binDir}:${process.env.PATH}`,
          },
        }
      );
      sendPromptInputs(proc);
      const result = await proc;
      expect(result.stdout).toContain('capsule.endor.dev');
    });
  });

  describe('Authentication failure', () => {
    it('displays an error indicating gh authentication is required', async () => {
      const binDir = createMockGh(1);
      const result = await execaNode(
        CLI_BIN,
        ['share', fixturePath('claude-session.jsonl')],
        {
          reject: false,
          env: {
            NO_COLOR: '1',
            PATH: `${binDir}:${process.env.PATH}`,
          },
        }
      );
      expect(result.stdout + result.stderr).toMatch(/auth/i);
    });

    it('does not attempt to create a Gist when authentication fails', async () => {
      const logFile = join(tempDir, 'gh-log.txt');
      const ghScript = join(mockBinDir, 'gh');
      const script = `#!/bin/sh
echo "$@" >> "${logFile}"
if [ "$1" = "auth" ] && [ "$2" = "status" ]; then
  exit 1
fi
if [ "$1" = "gist" ] && [ "$2" = "create" ]; then
  echo "https://gist.github.com/user/abc123"
  exit 0
fi
exit 1
`;
      writeFileSync(ghScript, script, 'utf-8');
      chmodSync(ghScript, 0o755);

      await execaNode(CLI_BIN, ['share', fixturePath('claude-session.jsonl')], {
        reject: false,
        env: {
          NO_COLOR: '1',
          PATH: `${mockBinDir}:${process.env.PATH}`,
        },
      });

      if (existsSync(logFile)) {
        const log = readFileSync(logFile, 'utf-8');
        expect(log).not.toContain('gist create');
      }
    });
  });
});

/**
 * ============================================================================
 * END OF AUTOGENERATED E2E TESTS
 *
 * Do not add manual tests below this line. They will be overwritten.
 * To add new test cases, update the E2E_TESTS.md specification.
 * ============================================================================
 */
